project_id = "cpbefoumpngamibpdtxu"

[functions.generate-monthly-invoices]
verify_jwt = true

[functions.send-settlement-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.cleanup-expired-trials]
verify_jwt = false
